In [1]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output
print("imported")

imported


In [2]:
env = gym.make("FrozenLake-v0")


In [3]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size,action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.15
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001


In [5]:
rewards_all_episodes = []

for episode in range(num_episodes):
    state = env.reset()

    done = False
    rewards_current_episode = 0

    for step in range(max_steps_per_episode):

        #exploration-exploitaion trade-off
        exploration_rate_threshold = random.uniform(0,1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:])
        else:
            action = env.action_space.sample()

        new_state, reward, done, info = env.step(action)

        q_table[state,action] = q_table[state,action]*(1-learning_rate) + learning_rate*(reward + discount_rate*np.max(q_table[new_state, :]))

        state = new_state
        rewards_current_episode += reward

        if done == True:
            break

    exploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate)*np.exp(-exploration_decay_rate*episode)

    rewards_all_episodes.append(rewards_current_episode)

rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000
print("Average reward per thousand episodes : ")
for r in rewards_per_thousand_episodes:
    print(count,": ",str(sum(r/1000)))
    count+=1000


Average reward per thousand episodes : 
1000 :  0.036000000000000025
2000 :  0.20900000000000016
3000 :  0.3960000000000003
4000 :  0.5220000000000004
5000 :  0.6240000000000004
6000 :  0.6340000000000005
7000 :  0.6750000000000005
8000 :  0.6880000000000005
9000 :  0.6940000000000005
10000 :  0.6770000000000005


In [6]:
print(q_table)

[[0.54418458 0.49842801 0.4984565  0.49827726]
 [0.22311104 0.36779981 0.32590803 0.47930619]
 [0.42300719 0.38233838 0.42532008 0.4484876 ]
 [0.35855259 0.31872453 0.20722533 0.4434908 ]
 [0.55774101 0.43930787 0.20281138 0.41575254]
 [0.         0.         0.         0.        ]
 [0.2800984  0.0762618  0.13400426 0.1135626 ]
 [0.         0.         0.         0.        ]
 [0.33958367 0.43945303 0.42636879 0.59231024]
 [0.51969175 0.6590396  0.30773953 0.34474478]
 [0.52312276 0.39277838 0.32692308 0.30390101]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.3847741  0.55290266 0.85690113 0.36659362]
 [0.68874715 0.89593558 0.68156516 0.68382853]
 [0.         0.         0.         0.        ]]


In [10]:
for episode in range(3):
    state = env.reset()
    done = False
    print("Episode : ",episode+1)

    time.sleep(2)

    for step in range(max_steps_per_episode):
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)

        action = np.argmax(q_table[state,:])

        new_state, reward, done, info = env.step(action)

        if done:
            clear_output(wait=True)
            env.render()
            if reward == 1:
                print("you reached the goal")
            else:
                print("you didn't reach the goal")
                time.sleep(1)
            
            break
        state = new_state

env.close()



  (Down)
SFFF
FHFH
FFFH
HFFG
you reached the goal
